### ISSUE TITLE
Starting container fails with read_only: true

### ISSUE THREAD

**Issue by sormu** [factoriotools/factorio-docker#263]
When adding read_only the container wont start.

Logs:
```
...
default_1  | + '[' 0 '=' 0 ]
default_1  | + usermod -o -u 845 factorio
default_1  | usermod: no changes
default_1  | + groupmod -o -g 845 factorio
default_1  | groupmod: /etc/group.18: Read-only file system
default_1  | groupmod: cannot lock /etc/group; try again later.
```

docker-compose.yml
```
version: '2.4'
services:
  default:
    image: dtandersen/factorio:latest
    ports:
    - "34197:34197/udp"
    - "27015:27015/tcp"
    volumes:
    - /mnt/ssd/docker/factorio:/factorio
    read_only: true
```
