### ISSUE TITLE
0.18.25 - no longer starting due to missing files

### ISSUE THREAD

**Issue by bplein** [factoriotools/factorio-docker#317]
I have a long running set of game servers using this container. They failed to come up with 0.18.25 image.

Here is the relevant error:
```
   0.884 Info PlayerData.cpp:68: Local player-data.json available, timestamp 1589925687
   0.884 Info PlayerData.cpp:75: Cloud player-data.json unavailable
   0.886 Factorio initialised
   0.887 Error CommandLineMultiplayer.cpp:372: Hosting multiplayer game failed: filesystem error: directory iterator cannot open directory: No such file or directory [/opt/factorio/saves]
   0.889 Info ServerMultiplayerManager.cpp:136: Quitting multiplayer connection.
   0.889 Info ServerMultiplayerManager.cpp:771: updateTick(4294967295) changing state from(Ready) to(Closed)
   0.923 Goodbye

```
Here is my docker-compose template:
```
version: '2.2'
services:
  factorio:
    image: "factoriotools/factorio:${LATEST}"
#    cpus: 2
#    cpuset: $MYCPU
    mem_limit: 12G
    mem_reservation: 4G
    restart: always
    network_mode: bridge
    ports:
     - "${GAME_PORT}:${GAME_PORT}/udp"
     - "${RCON_PORT}:${RCON_PORT}/tcp"
    environment:
      - PORT=${GAME_PORT}
      - RCON_PORT=${RCON_PORT}
      - UPDATE_MODS_ON_START=true
    container_name: "${CONTAINER_NAME}"
    volumes:
     - ./volume:/factorio
     - ../scenarios:/factorio/scenarios
     - ${PWD}/volume/config/config.ini:/opt/factorio/config/config.ini
    stdin_open: true
    tty: true
```

Did anything change about symlinks etc inside the image? My saves are locally under /volume/saves which in game is mounted to /factorio/saves and I think symlinked by the container image to /opt/factorio/saves.

Let me know. Thanks.
