### ISSUE TITLE
Multiple servers port conflict

### ISSUE THREAD

**Issue by Pyroseza** [factoriotools/factorio-docker#344]
Last night I tried hosting a secondary server, I followed the instructions by setting the docker-compose.yml file to have an inbound port forwarding rule of `34198:34197`, now this seems all fine and dandy for a local setup and if you are able to connect directly to a server, however... if you just want to broadcast a name for other people on the internet to just search and connect they would accidentally connect to your server running on port 34197, now this is not a fault on their side or with Factorio server matching but rather a bug in this repository's `Dockerfile` and the `docker-entrypoint.sh` script. 

So after a few minutes of careful debugging I concluded that the problem is because the port is hard coded and cannot be overwritten by setting your own `PORT` environment variable, it just gets overwritten by the Dockerfile.

I think the right way to do this is to have a whole new variable called whatever you want for me I'd go for something like `CUSTOM_PORT` and set that to what you want, then that way in the start up script check if it exists and if it does then use the custom port and assign it to the PORT variable.

Then continue as normal, I'll work on a fix right away and submit a pull request.

**Comment by SuperSandro2000** [comment]
You should be able to change the [port in the ENV section](https://github.com/factoriotools/factorio-docker/blob/ff432200f02acd0be6f55be1a2634e9f8b2046ba/1.0/Dockerfile#L10) and built yourself a custom image. This is not ideal but I consider this image complete and don't really want to add any new complicated mechanisms. So if your patch is just a few lines I would accept it but if it needs to change a lot I need to think about it.

**Comment by Pyroseza** [comment]
yes it is indeed just a few lines, unfortunately I could not get it to override the default port at all

I'm actually struggling to build the docker image as I don't have the files required, busy looking for and downloading them, unless you can point me to a bootstrap script that helps with this

**Comment by Pyroseza** [comment]
I think it was actually successful just the color of my terminal throwing me off :)
testing now...

**Comment by Pyroseza** [comment]
Success!
PR on it's way :D

**Comment by Pyroseza** [comment]
all done and tested on my side 👍 
https://github.com/factoriotools/factorio-docker/pull/345

**Comment by bplein** [comment]
I'm not sure I understand the issue: I have been running 5 servers on the same docker host for months. Here is my docker-compose.yml setup:

```
version: '2.2'
services:
  factorio:
    image: "factoriotools/factorio:${LATEST}"
    mem_limit: 12G
    mem_reservation: 4G
    restart: always
    ports:
     - "${GAME_PORT}:${GAME_PORT}/udp"
     - "${RCON_PORT}:${RCON_PORT}/tcp"
    environment:
      - PORT=${GAME_PORT}
      - RCON_PORT=${RCON_PORT}
      - UPDATE_MODS_ON_START=true
    container_name: "${CONTAINER_NAME}"
    volumes:
     - ./volume:/factorio
     - ../scenarios:/factorio/scenarios
    stdin_open: true
    tty: true
```

I set the environment variables before I call docker-compose...
