### ISSUE TITLE
Possibly a docker issue: "Determining own address has failed" when starting multiple Factorio containers simultaneously.

### ISSUE THREAD

**Issue by bplein** [factoriotools/factorio-docker#385]
This may be a limitation of Docker, but I'll post it here to get your input.

I run 5 containers of factorio using this project's image, all on the same host. I use docker-compose and pass in the differences to it using environment variables. 

If I restart a container individually, all is well. But if I do a mass restart (for example, the image is updated, my cron job sees this and in parallel all 5 get restarted), then the ping pong server picks up the wrong UDP port.  The container port expose IS correctly exposed (I can test it with netcat) and the container is listening on the correct port, but ping pong gets confused.

This could be a docker issue.  I wanted to see if you've seen this before. Right now I'm looking at having to write code that scrapes the log files after a restart to determine if it came up correctly. If anyone else has ideas on "health check" for factorio containers, that would be helpful!

Anyhow, here's the docker-compose template I use (I read in a file that holds the values for each server... and ${LATEST} is set to the specific version that is latest, not "latest":

**_docker-compose-template.yml_**
```
version: '2.2'
services:
  factorio:
    image: "factoriotools/factorio:${LATEST}"
    mem_limit: 12G
    mem_reservation: 4G
    restart: always
    ports:
     - "${GAME_PORT}:${GAME_PORT}/udp"
     - "${RCON_PORT}:${RCON_PORT}/tcp"
    environment:
      - PORT=${GAME_PORT}
      - RCON_PORT=${RCON_PORT}
      - UPDATE_MODS_ON_START=true
    container_name: "${CONTAINER_NAME}"
    volumes:
     - ./volume:/factorio
     - ../scenarios:/factorio/scenarios
    stdin_open: true
    tty: true
    entrypoint: ["/docker-entrypoint.sh", "--verbose"]
```
