### ISSUE TITLE
Error on Server load with latest docker image

### ISSUE THREAD

**Issue by leouzz** [factoriotools/factorio-docker#411]
fail to load the game
`   0.000 Error Util.cpp:83: filesystem error: cannot make canonical path: Operation not permitted [/opt/factorio/bin/x64/../../config/config.ini]`

**Comment by s-bauer** [comment]
Having the same issue!

**Comment by ianchak** [comment]
Is there any fix for this issue?

**Comment by Fank** [comment]
Will look into this tomorrow

**Comment by AgenttiX** [comment]
We're having the same issue as well. The save worked fine in 1.1.38, and we're using the following mods:
- [Bottleneck](https://mods.factorio.com/mods/trold/Bottleneck) 0.11.7
- [Even Distribution](https://mods.factorio.com/mod/even-distribution) 1.0.10
- [Far Reach](https://mods.factorio.com/mod/far-reach) 1.1.0
- [Factorio Library](https://mods.factorio.com/mod/flib) 0.8.3
- [Factory Planner](https://mods.factorio.com/mod/factoryplanner) 1.1.25
- [Squeak Through](https://mods.factorio.com/mod/Squeak%20Through) 1.8.2

Unfortunately it seems that a new autosave is created every time the server crashes, and therefore our old autosaves have been overwritten with 1.1.39 ones, so we can't continue playing by reverting to an older version, as the 1.1.39 saves can't be loaded in 1.1.38. Therefore it might be a good idea to add such a feature to the container that it would create a copy of the saves directory when it detects that it has been updated. (Our container was accidentally updated automatically by an unrelated [Ouroboros](https://github.com/pyouroboros/ouroboros) container running on the same host, so we didn't manage to create backups before the upgrade.)

Here's our `docker-compose.yml`.
```
version: "3"
services:
  factorio:
    image: factoriotools/factorio
    ports:
      - "34197:34197/udp"
      - "27015:27015/tcp"
    volumes:
      - "./data:/factorio"
    restart: always
```

**Comment by MacaroonCookie** [comment]
I'm having the same issue. The error I am receiving is (full logs found in [Pastebin](https://paste.ubuntu.com/p/hn2GcK6KVy/)):
```
sg-factorio |    0.000 Error Util.cpp:83: filesystem error: cannot make canonical path: Operation not permitted [/opt/factorio/bin/x64/../../config/config.ini]
```

I'm running:
* Docker Hub image - factoriotools/factorio:1.139, digest 1728560e0470
* Docker Version - 19.03.8 CE
* Docker Storage Driver: overlay2
* OS - Ubuntu 20.04 LTS (Focal Fossa) Server

I have reproduced the error by using an existing save, and by attempting to generate a new save using the following Docker Compose file:
```
version: "3.3"
services:
    factorio:
        container_name: sg-factorio
        image: factoriotools/factorio:stable
        restart: unless-stopped
        ports:
            - "34197:34197/udp"
            - "27015:27015/tcp"
        volumes:
            - "/opt/factorio:/factorio"
        environment:
            SAVE_NAME: testsave
            GENERATE_NEW_SAVE: 'true'
            LOAD_LATEST_SAVE: 'false'
```

Actions I have taken:
* Set the `/opt/factorio` directory ownership is set to `845:845` (required by default)
* Tested on 1.1.38 save
* Tested by generating a new save
* Removed all factoriotools/factorio images
* Rebooted host
