### ISSUE TITLE
Laggy Server when Deployed to Kubernetes Cluster

### ISSUE THREAD

**Issue by lukasyelle** [factoriotools/factorio-docker#416]
I know I've made the deployment of my own Factorio server more complicated by deploying it via a HA Kubernetes Cluster (utilizing [SQLJames's Factorio Helm Chart](https://github.com/SQLJames/factorio-server-charts)) but nevertheless I was able to spin up the container and access the server both from within my network and externally after port-forwarding the game port and setting up an ingress into the cluster.

I've noticed that, although sometimes the game is quite playable from within my network (getting 60UPS and 60FPS consistently), every now and then (even internally) I get huge latency spikes and I get booted from the server. As soon as I leave the house the latency issue is exasperated greatly and I am able to play (if I'm lucky) for just minutes before again getting booted. I'd like to keep the server running in the cluster if possible, so if anyone has had similar issues and figured out a solution, any tips / tricks would be greatly appreciated.

As an aside I've also spun up a Minecraft server on the same cluster with [itzg's helm chart](https://github.com/itzg/minecraft-server-charts). This server consistently gets ~20ms ping and no latency issues from outside of the network, so my connection does not seem to be the issue.

**Comment by bplein** [comment]
What CNI are you using? Any details about your configuration would be helpful.

**Comment by SQLJames** [comment]
@lukasyelle I am not sure if you were able to solve this, but what were your resource utilizations? Also were you using any mods? Ive run into a few issues with mods on the deployment when I wasn't giving the pod enough resources to start.

try increasing the requests in the value.yaml file
```
## Compute Resources required by the operator container
resources:
  ## We have to ensure that factorio have enough computing resources avaiable. We set here an absolute minimum
  ## Keep in mind that big factorio base can consume a lot of memory and cpu
  requests:
    memory: 512Mi
    cpu: 500m
    ```
