### ISSUE TITLE
Disable SHA verification/getting the newest hash automatically

### ISSUE THREAD

**Issue by DoomOfMax97** [factoriotools/factorio-docker#456]
Hi,

is there a way to disable the hash verification or to make sure the server is automatically updated to the latest version?
Even if I use the 'latest' branch it doesn't work after an update, do I always need to manually update the SHA-Hash or am I doing something wrong?

Regards
Doom

**Comment by LsHallo** [comment]
I think you might be using this project wrong.
You will just use the prebuilt image factoriotools/factorio:latest in you docker compose. No SHA is involved in that step that you need to update. You don't need to run docker build yourself on every update.
Just use the latest image and run docker pull to update youe local image.

**Comment by LsHallo** [comment]
Example compose file:
```
services:
  factorio:
    image: factoriotools/factorio:latest
    container_name: factorio
    restart: unless-stopped
    ports:
      - "34197:34197/udp"
    volumes:
      - /opt/factorio:/factorio
```
