### ISSUE TITLE
how to update..

### ISSUE THREAD

**Issue by nkucza** [factoriotools/factorio-docker#463]
Hey, i am relatively new to docker and so on..
yesterday the new version was released and I am not sure how to update the factorio server.

It is running with portainer and the stack

```
version: '2'
services:
  factorio:
    image: factoriotools/factorio:latest
    ports:
     - "6262:34197/udp"
     - "6262:27015/tcp"
    volumes:
     - /opt/factorio:/factorio
    restart: unless-stopped
```

what do I need to do to get it to 1.1.80?
