### ISSUE TITLE
Unable to run with Rootless Docker configuration.

### ISSUE THREAD

**Issue by ScidaJ** [factoriotools/factorio-docker#496]
Hello, I have a little server box running NixOS, and I'm trying to launch the container to complete the setup, however the container fails to launch with the error 
`chown: changing ownership of '/factorio': Operation not permitted`
The line that fails is 
`chown -R factorio:factorio /factorio`

I have followed all of the setup instructions as best I could, but solving this issue has eluded me.

I launch the container using `docker-compose up -d`, as my Docker is configured `Rootless` as is described in the [NixOS](https://nixos.wiki/wiki/Docker) and [Docker](https://docs.docker.com/engine/security/rootless/) documentation.

Any help is appreciated.

**Comment by gabevenberg** [comment]
Could you share your relevant nix config snippets?

**Comment by ScidaJ** [comment]
Hi, this is my Docker config in my `configuration.nix` file.
```
# Virtualisation Configuration
  virtualisation.docker.rootless = {
    enable = true;
    setSocketVariable = true;
  };
```

I have an existing save that I was looking to transfer over but that was something to be done after the server was up and running on that machine, so I was using the example Docker Compose configuration in the README for the Factorio server.

```
version: '2'
services:
  factorio:
    image: factoriotools/factorio
    ports:
     - "34197:34197/udp"
     - "27015:27015/tcp"
    volumes:
     - /opt/factorio:/factorio
```
If you need any other information please let me know, thank you.
