### ISSUE TITLE
Github action failure

### ISSUE THREAD

**Issue by oskar-evimeria** [factoriotools/factorio-docker#502]

**Comment by miragecentury** [comment]
Due to sha check ? The commit miss the checksum value.

**Comment by miragecentury** [comment]
Fixed in https://github.com/factoriotools/factorio-docker/pull/503

**Comment by oskar-evimeria** [comment]
Guessing latest releases (https://factorio.com/api/latest-releases) as updated before the sha hash in https://factorio.com/download/sha256sums/
They are present now.

**Comment by Sculas** [comment]
For the ones who want it *now* and don't want to wait until it's officially fixed (Linux only, change it to suit your needs):

Run the following:
```
wget https://factorio.com/get-download/stable/headless/linux64 -O linux.tar.xz
tar xf linux.tar.xz
rm linux.tar.xz
sudo chown -R 845:845 factorio
```
Update your docker-compose file:
```yaml
services:
  factorio:
    # ...
    volumes:
      - ./data:/factorio
      - ./factorio/bin:/opt/factorio/bin:ro
      - ./factorio/data:/opt/factorio/data:ro
```
Make sure to delete your `data` directory (this WILL delete your save and settings, back it up!) to start a new 2.0 save with all the new things. Copy over your old server settings from the backup you made earlier if you want to keep them. Have fun!
