### ISSUE TITLE
Error when creating server game: Missing token since the DLC Launch

### ISSUE THREAD

**Issue by CupCacke** [factoriotools/factorio-docker#507]
Greetings, 

I´ve encounterd the issue that all my servers run into the issue "Error when creating server game: Missing token."

I reset my token and tryid that of another "working container" so I ensured the token did not expire.

Any ideas?

**Comment by LewisMcFly** [comment]
Same here. If you fix this please share the details.

**Comment by LewisMcFly** [comment]
@CupCacke I fixed it by adding the `CONFIG`  environment variable, forcing it to `/opt/factorio/config`.

**Comment by CupCacke** [comment]
I´ve deletet all the local files from the container so it created them from scratch.

**Comment by Gornoka** [comment]
This is due to a changed / enforce default value, the default config value for public = true + no token, means that the server does not start with the default config.

For some reason the env var toke is also not used correctly.

Imho the default behaviour should be that your Factorio server is private anyways, unless you want it to be publi. 

Therefore the default value should be:

````json
  "visibility": {
    "public": false,
    "lan": true
  },
````

used compose file to reproduce the issue:

````yaml
x-logging:
  logging: &default-logging
    driver: "local"
    options:
      max-size: "100m"
      max-file: "3"
version: '3.7'
services:
  factorio:
    image: factoriotools/factorio:2.0
    logging: *default-logging
    ports:
     - "34197:34197/udp"
     # - "27024:27015/tcp"
    #restart: unless-stopped
    environment:
      UPDATE_MODS_ON_START: true
    volumes:
     - /var/some_magic_location/factorio_2024_se:/factorio
````
