### ISSUE TITLE
Lan Browsing not working

### ISSUE THREAD

**Issue by LawrenceSpear** [factoriotools/factorio-docker#536]
Was working on my old NAS with version 1, but when upgrading to version 2 on new NAS it stopped. I'm able to connect via public and direct IP connect, but Browse LAN it doesn't show up.

YAML has the ports open and on host network
```
version: "3.5"
services:
  factorio:
    image: factoriotools/factorio:2.0.10
    ports:
      - "34197:34197/udp"
      - "27015:27015/tcp"
    container_name: factorio
    network_mode: 'host'
    volumes:
      - /volume1/docker/factorio/data:/factorio
    restart: unless-stopped
    environment:
      - UPDATE_MODS_ON_START=true
```

and in server-settings.json I have:

"visibility": {
    "public": true,
    "lan": true
  },

In the log I see: Info RemoteCommandProcessor.cpp:129: Starting RCON interface at IP ADDR:({0.0.0.0:27015})

So it seeming to be configured correctly
