### ISSUE TITLE
[Support] Easier updating of docker-compose instance? (SHA256)

### ISSUE THREAD

**Issue by ividyon** [factoriotools/factorio-docker#552]
First off, the project works wonderfully, thank you very much.

Currently, whenever I want to upgrade the server to one of the many, many updates of Factorio, it's not enough to just set version to latest. I have to also procure the latest SHA256 from the buildinfo.json file. This seems to defeat the point of having a version tagged "latest" in the first place.

Can you suggest/implement a way of being able to just provide a version number, or even just "latest", and have the SHA256 be grabbed from buildinfo.json automatically?

**Comment by AidanHarveyNelson** [comment]
Not sure exactly what you are having issues with my docker compose looks like this 
```
  factorio:
    container_name: factorio
    hostname: factorio
    image: factoriotools/factorio:stable
    ports:
      - 34197:34197/udp
      - 27015:27015/tcp
    volumes:
      - ${CONFIG_MOUNT_PATH}/factorio:/factorio
    environment:
      - LOAD_LATEST_SAVE=false
      - SAVE_NAME=factorio
    restart: unless-stopped
```
Then I have a scheduled job on my server that checks every hour whether the server needs to be updated such as 
`docker-compose up --pull always -d factorio`. Thus as soon as the update goes live and is pushed to the stable branch the docker image will automatically pull the image down and restart the container, if no update it does nothing

Are you building the image from scratch each time?
