### ISSUE TITLE
cannot create directory '/factorio/saves': Permission denied

### ISSUE THREAD

**Issue by icheered** [factoriotools/factorio-docker#555]
On a fresh docker-compose on my nixos system running docker in rootless mode I get the error in the title. 
```bash
mkdir my_factorio
sudo chown 845:845 my_factorio
docker-compose up factorio
```

My `docker-compose.yml`:
```yml
  factorio:
    image: factoriotools/factorio:2.0.21
    container_name: factorio
    ports:
      - "34197:34197/udp"
      - "27015:27015/tcp"
    volumes:
      - ./my_factorio:/factorio
    restart: unless-stopped
    stdin_open: true
    tty: true
```

I am running NixOS.
