### ISSUE TITLE
Connection loop with missing mods

### ISSUE THREAD

**Issue by Bagu** [factoriotools/factorio-docker#559]
Hello,
After taking a break for several years, I've decided to relaunch a Factorio server.
But I've run into a problem.
My composite docker is as follows:

```
version: ‘3.8
services:
  factorio:
    container_name: ‘factorio’
    image: ‘factoriotools/factorio:stable’
    ports:
      - ‘34197:34197/udp’
      - ‘27015:27015/tcp’
    volumes:
      - ‘/volume1/docker/appdata/factorio:/factorio’
    restart: unless-stopped
```

The container launches successfully.
But when I try to connect, I get a loop telling me that my mods are not synchronised with those on the server. (space-age elevated-rails quality are missing but cannot be downloaded)
So I set these 3 mods to false, but nothing happens.
Do you have a way for me to finally connect?
Thanks
