### ISSUE TITLE
Compose example is awful

### ISSUE THREAD

**Issue by Lizardbutt** [factoriotools/factorio-docker#560]
Please update your compose example. It's silly to even need to manually chown an opt directory as it's against the fundamentals of linux, just path it to a local directory and you can completely skip that step.

```yaml
version: '2'
services:
  factorio:
    image: factoriotools/factorio
    restart: always
    container_name: factorio-server
    ports:
     - 34197:34197/udp
     - 27015:27015/tcp
    volumes:
     - "./factorioData:/factorio"
    environment:
     - PUID=1000
     - PGID=1000
     - USERNAME=FactorioProfileName
     - TOKEN=FactorioProfileToken
     - PRESET=Default
```
