### ISSUE TITLE
Docker compose DLC_SPACE_AGE variable does nothing

### ISSUE THREAD

**Issue by JOSEALM3IDA** [factoriotools/factorio-docker#562]
I am running the following docker compose:

```
version: "2"
services:
  factorio:
    container_name: factorio
    image: factoriotools/factorio:stable
    restart: unless-stopped
    ports:
      - "34197:34197/udp" # game server
      - "27015:27015/tcp" # rcon (optional)
    volumes:
      - ./data:/factorio
    environment:
      - DLC_SPAGE_AGE=false 
```

The space age mods still get enabled (verifiable in ./data/mods/mod-list.json)

I also cannot change the file manually, since when the server shuts down, it overrides the file anyways, and doesn't respect anything there on boot

Either something is badly documented, or this is a bug. Any explanation?
